
SELECT 
    CAST(AIR_TEMPERATURE AS FLOAT) AS AIR_TEMPERATURE,  
    CAST(DATE AS TIMESTAMP_NTZ) AS DATE,  
    CAST(HUMIDITY AS FLOAT) AS HUMIDITY,  
    CAST(MEETING_KEY AS INT) AS MEETING_KEY,  
    CAST(SESSION_KEY AS INT) AS SESSION_KEY,  
    CAST(PRESSURE AS FLOAT) AS PRESSURE,  
    CAST(RAINFALL AS INT) AS RAINFALL,  
    CAST(TRACK_TEMPERATURE AS FLOAT) AS TRACK_TEMPERATURE,  
    CAST(WIND_DIRECTION AS INT) AS WIND_DIRECTION,  
    CAST(WIND_SPEED AS FLOAT) AS WIND_SPEED,  

    -- Handling missing values: Fill missing AIR_TEMPERATURE with the average value
    COALESCE(AIR_TEMPERATURE, (
        SELECT AVG(AIR_TEMPERATURE) 
        FROM {{ ref('STG_API_WEATHER') }}
    )) AS AIR_TEMPERATURE_FILLED,

    -- Create derived features, e.g., Heat Index and Wind Chill
    CASE 
        WHEN AIR_TEMPERATURE IS NOT NULL AND HUMIDITY IS NOT NULL THEN
            AIR_TEMPERATURE + (0.55 * (1 - HUMIDITY / 100) * (AIR_TEMPERATURE - 58))
        ELSE NULL
    END AS HEAT_INDEX,

    CASE
        WHEN AIR_TEMPERATURE IS NOT NULL AND WIND_SPEED IS NOT NULL THEN
            AIR_TEMPERATURE - (0.7 * WIND_SPEED) -- Wind Chill simplified formula
        ELSE NULL
    END AS WIND_CHILL

FROM {{ ref('STG_API_WEATHER') }}

{% if is_incremental() %}
    {{ incremental_date_comparison() }}
{% endif %}
