SELECT 
    COALESCE(CAST(COMPOUND AS STRING), 'NO_TYRE') AS COMPOUND,  
    CAST(DRIVER_NUMBER AS INT) AS DRIVER_NUMBER,  
    CAST(LAP_START AS INT) AS LAP_START,  
    CAST(LAP_END AS INT) AS LAP_END,  
    CAST(MEETING_KEY AS INT) AS MEETING_KEY,  
    CAST(SESSION_KEY AS INT) AS SESSION_KEY,  
    CAST(STINT_NUMBER AS INT) AS STINT_NUMBER,  
    COALESCE(CAST(TYRE_AGE_AT_START AS INT), -1) AS TYRE_AGE_AT_START  
FROM {{ ref('STG_API_STINTS') }}

{% if is_incremental() %}
    {{ incremental_session_meeting_key() }}
{% endif %}
