"""
get_activity
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum

from airflow.models import Variable
import requests

@aql.dataframe(task_id="fetch_activity")
def fetch_activity_func():
    print("Hello")

default_args={
    "owner": "Nama Saya Elvis,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2025-01-17", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Nama Saya Elvis": "mailto:elvischan031@gmail.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/cm5qcuuw6061v01lt8oi1qib3/cloud-ide/cm604m85c0h7501nc0l8b8qzp/cm604obf00h7d01nsor3ivwom",
    },
)
def get_activity():
    fetch_activity = fetch_activity_func()

dag_obj = get_activity()
