SELECT *
FROM {{ source('ASTON_MARTIN_DATA', 'PIT_API') }}
WHERE COALESCE(
    NULLIF(PIT_DURATION, ''), 
    NULLIF(LAP_NUMBER, ''), 
    NULLIF(DRIVER_NUMBER, ''), 
    NULLIF(SESSION_KEY, ''), 
    NULLIF(MEETING_KEY, '')
) IS NOT NULL