SELECT *
FROM {{ source('ASTON_MARTIN_DATA', 'RACE_CONTROL_API') }}
WHERE COALESCE(
    NULLIF(CATEGORY, ''), 
    NULLIF(FLAG, ''), 
    NULLIF(SCOPE, ''), 
    NULLIF(MESSAGE, ''), 
    NULLIF(SESSION_KEY, ''), 
    NULLIF(MEETING_KEY, ''), 
    NULLIF(DRIVER_NUMBER, ''), 
    NULLIF(LAP_NUMBER, ''), 
    NULLIF(SECTOR, '')
) IS NOT NULL
