SELECT *
FROM {{ source('ASTON_MARTIN_DATA', 'SESSIONS_API') }}
WHERE COALESCE(
    NULLIF(LOCATION, ''), 
    NULLIF(COUNTRY_KEY, ''), 
    NULLIF(COUNTRY_CODE, ''), 
    NULLIF(COUNTRY_NAME, ''), 
    NULLIF(CIRCUIT_KEY, ''), 
    NULLIF(CIRCUIT_SHORT_NAME, ''), 
    NULLIF(SESSION_TYPE, ''), 
    NULLIF(SESSION_NAME, ''), 
    NULLIF(DATE_START, ''), 
    NULLIF(DATE_END, ''), 
    NULLIF(GMT_OFFSET, ''), 
    NULLIF(SESSION_KEY, ''), 
    NULLIF(MEETING_KEY, ''), 
    NULLIF(YEAR, '')
) IS NOT NULL