SELECT
    RACEID,
    YEAR,
    ROUND,
    CIRCUITID,
    NAME,
    DATE,
    CASE WHEN TIME = '\\N' THEN NULL ELSE TIME END AS TIME,
    URL,    
    -- Replace '\N' with NULL using a CASE statement
    CASE WHEN FP1_DATE = '\\N' THEN NULL ELSE FP1_DATE END AS FP1_DATE,
    CASE WHEN FP1_TIME = '\\N' THEN NULL ELSE FP1_TIME END AS FP1_TIME,
    CASE WHEN FP2_DATE = '\\N' THEN NULL ELSE FP2_DATE END AS FP2_DATE,
    CASE WHEN FP2_TIME = '\\N' THEN NULL ELSE FP2_TIME END AS FP2_TIME,
    CASE WHEN FP3_DATE = '\\N' THEN NULL ELSE FP3_DATE END AS FP3_DATE,
    CASE WHEN FP3_TIME = '\\N' THEN NULL ELSE FP3_TIME END AS FP3_TIME,
    CASE WHEN QUALI_DATE = '\\N' THEN NULL ELSE QUALI_DATE END AS QUALI_DATE,
    CASE WHEN QUALI_TIME = '\\N' THEN NULL ELSE QUALI_TIME END AS QUALI_TIME,
    CASE WHEN SPRINT_DATE = '\\N' THEN NULL ELSE SPRINT_DATE END AS SPRINT_DATE,
    CASE WHEN SPRINT_TIME = '\\N' THEN NULL ELSE SPRINT_TIME END AS SPRINT_TIME

FROM {{ source('ASTON_MARTIN_DATA', 'RACES') }} 