SELECT *
FROM {{ source('ASTON_MARTIN_DATA', 'POSITION_API') }}
WHERE COALESCE(
    NULLIF(DATE, ''), 
    NULLIF(DRIVER_NUMBER, ''), 
    NULLIF(MEETING_KEY, ''), 
    NULLIF(POSITION, ''), 
    NULLIF(SESSION_KEY, '')
) IS NOT NULL