SELECT *
FROM {{ source('ASTON_MARTIN_DATA', 'WEATHER_API') }}
WHERE COALESCE(
    NULLIF(AIR_TEMPERATURE, ''), 
    NULLIF(HUMIDITY, ''), 
    NULLIF(PRESSURE, ''), 
    NULLIF(RAINFALL, ''), 
    NULLIF(TRACK_TEMPERATURE, ''), 
    NULLIF(WIND_DIRECTION, ''), 
    NULLIF(WIND_SPEED, ''), 
    NULLIF(SESSION_KEY, ''), 
    NULLIF(MEETING_KEY, '')
) IS NOT NULL
