SELECT *
FROM {{ source('ASTON_MARTIN_DATA', 'STINTS_API') }}
WHERE COALESCE(
    NULLIF(MEETING_KEY, ''), 
    NULLIF(SESSION_KEY, ''), 
    NULLIF(STINT_NUMBER, ''), 
    NULLIF(DRIVER_NUMBER, ''), 
    NULLIF(LAP_START, ''), 
    NULLIF(LAP_END, ''), 
    NULLIF(COMPOUND, ''), 
    NULLIF(TYRE_AGE_AT_START, '')
) IS NOT NULL