-- no transformation needed

SELECT
    CONSTRUCTORSTANDINGSID as CONSTRUCTOR_STANDINGS_ID,
    RACEID as RACE_ID,
    CONSTRUCTORID as CONSTRUCTOR_ID,
    POINTS,
    POSITION,
    WINS
FROM {{ source('ASTON_MARTIN_DATA', 'CONSTRUCTOR_STANDINGS') }}