name: Snowflake CSV Upload & Load

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch
  schedule:
    - cron: "0 1 * * *"  # Scheduled to run at 1 AM Singapore Time every day

jobs:
  upload-and-load:
    runs-on: ubuntu-22.04  # Use Ubuntu-based runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install SnowSQL
      - name: Download and install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
          SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
          echo "export PATH=\$PATH:~/snowflake/snowsql" >> ~/.profile
          source ~/.profile

      # Step 3: Test SnowSQL installation
      - name: Test SnowSQL installation
        run: |
          source ~/.profile
          ~/snowflake/snowsql -v

      # Step 4: Set up Snowflake credentials
      - name: Set up Snowflake credentials
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          echo "[connections.default]" > $HOME/.snowsql/config
          echo "accountname = ${SNOWFLAKE_ACCOUNT}" >> $HOME/.snowsql/config
          echo "username = ${SNOWFLAKE_USER}" >> $HOME/.snowsql/config
          echo "password = ${SNOWFLAKE_PASSWORD}" >> $HOME/.snowsql/config
          echo "dbname = ${SNOWFLAKE_DATABASE}" >> $HOME/.snowsql/config
          echo "warehouse = ${SNOWFLAKE_WAREHOUSE}" >> $HOME/.snowsql/config
          echo "schemaname = ${SNOWFLAKE_SCHEMA}" >> $HOME/.snowsql/config

      # Step 5: Load CSV files from Snowflake stage into Snowflake tables
      - name: Load CSV files from Snowflake stage into tables
        run: |
          echo "Loading CSV files from Snowflake stage into tables..."
          # Loop through the files in the Snowflake stage and load them into corresponding tables
          for file in circuits.csv.gz pit_stops.csv.gz seasons.csv.gz constructor_results.csv.gz constructors.csv.gz races.csv.gz qualifying.csv.gz lap_times.csv.gz constructor_standings.csv.gz drivers.csv.gz circuits.csv.gz sprint_results.csv.gz driver_standings.csv.gz status.csv.gz results.csv.gz; do
            table_name=$(basename "$file" .csv.gz)  # Deriving table name from the file name
            echo "Loading $file into table $table_name"
            ~/snowflake/snowsql -c default -q "COPY INTO ${SNOWFLAKE_DATABASE}.${SNOWFLAKE_SCHEMA}.${table_name} FROM @$SNOWFLAKE_STAGE/$file FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 COMPRESSION = 'GZIP')"
          done

      # Step 6: Verify loading status (optional)
      - name: Verify loading status
        run: |
          echo "Verifying the load status..."
          for file in circuits.csv.gz pit_stops.csv.gz seasons.csv.gz constructor_results.csv.gz constructors.csv.gz races.csv.gz qualifying.csv.gz lap_times.csv.gz constructor_standings.csv.gz drivers.csv.gz circuits.csv.gz sprint_results.csv.gz driver_standings.csv.gz status.csv.gz results.csv.gz; do
            table_name=$(basename "$file" .csv.gz)
            echo "Checking row count for table $table_name"
            ~/snowflake/snowsql -c default -q "SELECT COUNT(*) FROM ${SNOWFLAKE_DATABASE}.${SNOWFLAKE_SCHEMA}.${table_name};"
          done
